### ISSUE TITLE
Class Nord\Lumen\Rbac\Contracts\RbacService does not exist

### ISSUE THREAD

**Issue by soderluk** [nordsoftware/lumen-core#4]
If one does not need the lumen-rbac in the project, lumen-core still depends on it in:
SerializerService.php:28 and SerializerService.php:92.

**Comment by cniska** [comment]
This is unfortunate, we will refactor the whole dependency graph for lumen-core at some point to fix this.

**Comment by cniska** [comment]
@kryysler can you take a look a this when you have time?

**Comment by cniska** [comment]
This has been fixed.
